Django/Learning/learning/forms/urls.py
from django.urls import path
from . import views

app_name = "forms"

urlpatterns = [
    path("", views.index, name="index"),
]

Django/Learning/learning/learning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('forms/', include('forms.urls')),
]

Django/Learning/learning/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add")
]

Django/Learning/learning/forms/models.py
from django.db import models

# Create your models here.
class GeeksModel(models.Model):
    title = models.CharField(max_length = 200)
    description = models.TextField()
    last_modified = models.DateTimeField(auto_now_add = True)
    img = models.ImageField(upload_to = "images/")


    def __str__(self):
        return self.title

Django/Learning/learning/tasks/models.py
from django.db import models

# Create your models here.

Django/Learning/learning/forms/admin.py
from django.contrib import admin
from .models import GeeksModel

# Register your models here.
admin.site.register(GeeksModel)

Django/Learning/learning/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forms'

Django/Learning/learning/forms/tests.py
from django.test import TestCase

# Create your tests here.

Django/Learning/learning/forms/views.py
from django.shortcuts import render
from django import forms

# Create your views here.
def index(request):
    context = {}
    context['form'] = InputForm()
    return render(request, "forms/index.html", context)

class GeeksForm(forms.Form):
    title = forms.CharField()
    description = forms.CharField()


class InputForm(forms.Form):
    first_name = forms.CharField(max_length = 200)
    last_name = forms.CharField(max_length = 200)
    roll_numner = forms.IntegerField(help_text = "Enter 6 digit roll number")
    password = forms.CharField(widget = forms.PasswordInput())

Django/Learning/learning/tasks/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponse

tasks = ["foo", "bar", "baz"]

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

# Create your views here.
def index(request):
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })


def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task) #Adding a new task to list of tasks
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
    return render(request, "tasks/add.html", {
                  "form": NewTaskForm()
    })

Django/Learning/learning/forms/templates/forms/index.html
OPORO

<!-- {{ form.as_p }} -->

<form action="" method="'post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

Django/Learning/learning/tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}

{% block body %}
    <h1>Add Task</h1> 
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %} <!-- Cross Site Request Forgery -->
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Task</a>
{% endblock %}

Django/Learning/learning/tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}

{% block body %}
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a New Task</a>
    {% endblock %}

Django/Learning/learning/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</html>